import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from fastapi import HTTPException

def generate_pdf_report(title: str, summary: str, predictions: list, output_path: str):
    """
    Generate a PDF report from predictions and summary.
    predictions: list of dicts with keys: 'result', 'confidence', 'timestamp'
    """
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.darkblue,
        spaceAfter=12
    )
    story.append(Paragraph(title, title_style))
    story.append(Spacer(1, 0.25*inch))

    # Generated summary
    summary_style = styles['Normal']
    story.append(Paragraph(summary, summary_style))
    story.append(Spacer(1, 0.25*inch))

    # Predictions table
    story.append(Paragraph("Prediction History", styles['Heading2']))
    story.append(Spacer(1, 0.1*inch))

    table_data = [["Date", "Stage", "Confidence"]]
    for p in predictions:
        date_str = p['timestamp'].strftime("%Y-%m-%d %H:%M")
        conf_str = f"{p['confidence']*100:.1f}%"
        table_data.append([date_str, p['result'], conf_str])

    table = Table(table_data, colWidths=[2*inch, 2*inch, 1.5*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.grey),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 12),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
        ('BACKGROUND', (0,1), (-1,-1), colors.beige),
        ('GRID', (0,0), (-1,-1), 1, colors.black),
    ]))
    story.append(table)

    # Footer
    story.append(Spacer(1, 0.5*inch))
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.grey,
        alignment=1  # center
    )
    story.append(Paragraph("Generated by NeuroSight AI", footer_style))

    doc.build(story)